import React, { useMemo } from 'react';
import { AlertCircle, CheckCircle2, Clock3, Database, RefreshCw, TriangleAlert } from 'lucide-react';
import type { DataHealthStatus, MarketDataQuality, MarketHub } from '../types';

interface MarketDataHealthProps { hubs: MarketHub[]; qualities: Record<number, MarketDataQuality>; isSyncing: boolean; onRefresh: () => void; }
const META: Record<DataHealthStatus,{label:string;tone:string;icon:React.ReactNode}>={
LIVE:{label:'LIVE',tone:'text-emerald-300 bg-emerald-500/10 border-emerald-500/30',icon:<CheckCircle2 className="w-3.5 h-3.5"/>},CACHE:{label:'CACHE',tone:'text-blue-300 bg-blue-500/10 border-blue-500/30',icon:<Database className="w-3.5 h-3.5"/>},STALE:{label:'STALE',tone:'text-amber-300 bg-amber-500/10 border-amber-500/30',icon:<Clock3 className="w-3.5 h-3.5"/>},PARTIAL:{label:'PARTIEL',tone:'text-orange-300 bg-orange-500/10 border-orange-500/30',icon:<TriangleAlert className="w-3.5 h-3.5"/>},UNKNOWN:{label:'INCONNU',tone:'text-zinc-300 bg-zinc-500/10 border-zinc-500/30',icon:<TriangleAlert className="w-3.5 h-3.5"/>},ERROR:{label:'ERREUR',tone:'text-red-300 bg-red-500/10 border-red-500/30',icon:<AlertCircle className="w-3.5 h-3.5"/>}};
const resolveHealth=(q?:MarketDataQuality):DataHealthStatus=>{if(!q)return 'UNKNOWN';if(q.health_status)return q.health_status;if(q.error_count>0&&q.orders_valid===0)return 'ERROR';if(q.completeness==='partial')return 'PARTIAL';if(q.source==='cache'||q.source==='indexeddb')return 'CACHE';if(q.freshness==='stale'||q.freshness==='expired')return 'STALE';if(q.source==='esi'&&q.validation_status==='valid')return 'LIVE';return 'UNKNOWN';};
const age=(s:number)=>!Number.isFinite(s)||s<0?'—':s<60?Math.round(s)+'s':s<3600?Math.round(s/60)+'m':Math.round(s/3600)+'h';
const diagnostics=(q?:MarketDataQuality)=>{if(!q)return '';const parts=[];if(q.last_http_status!==undefined)parts.push('HTTP '+q.last_http_status);if(q.cache_status)parts.push('cache '+q.cache_status);if(q.pages_fetched&&q.expected_pages)parts.push('pages '+q.pages_fetched+'/'+q.expected_pages);if(q.esi_error_limit_remaining!==undefined)parts.push('budget ESI '+q.esi_error_limit_remaining);if(q.retry_after_seconds!==undefined)parts.push('retry '+q.retry_after_seconds+'s');return parts.join(' · ');};
export const MarketDataHealth:React.FC<MarketDataHealthProps>=({hubs,qualities,isSyncing,onRefresh})=>{const states=useMemo(()=>hubs.filter(h=>h.active).map(h=>({hub:h,quality:qualities[h.region_id],health:resolveHealth(qualities[h.region_id])})),[hubs,qualities]);const aggregate=useMemo<DataHealthStatus>(()=>{if(!states.length)return 'UNKNOWN';if(states.some(s=>s.health==='ERROR'))return 'ERROR';if(states.some(s=>s.health==='PARTIAL'))return 'PARTIAL';if(states.some(s=>s.health==='STALE'))return 'STALE';if(states.some(s=>s.health==='UNKNOWN'))return 'UNKNOWN';if(states.some(s=>s.health==='CACHE'))return 'CACHE';return 'LIVE';},[states]);if(!states.length)return null;const meta=META[aggregate];const problem=aggregate!=='LIVE'||states.some(s=>(s.quality?.error_count??0)>0);return <section aria-label="État des données du marché" className={problem?'bg-[#161821] border-b border-amber-500/20 px-4 sm:px-6 py-2.5':'bg-[#161821] border-b border-[#262730] px-4 sm:px-6 py-2'}><div className="flex flex-wrap items-center gap-2.5"><div className="flex items-center gap-2"><span className="text-[10px] uppercase tracking-wider font-semibold text-[#808495]">Données marché</span><span className={'inline-flex items-center gap-1.5 px-2 py-0.5 rounded border text-[10px] font-bold '+meta.tone}>{meta.icon}{meta.label}</span></div><div className="flex items-center gap-1.5 flex-wrap">{states.map(({hub,quality,health})=>{const m=META[health];const diag=diagnostics(quality);const title=quality?.last_error?hub.name+': '+quality.last_error+(diag?' · '+diag:''):hub.name+': '+m.label+', âge '+age(quality?.age_seconds??0)+', '+(quality?.orders_valid??0)+' ordres'+(diag?' · '+diag:'');return <span key={hub.id} title={title} className={'inline-flex items-center gap-1 px-2 py-0.5 rounded border text-[10px] '+m.tone}><span className="font-semibold">{hub.name}</span><span className="opacity-80">{m.label}</span>{quality&&<span className="font-mono opacity-70">{age(quality.age_seconds)}</span>{quality?.last_http_status&&<span className="font-mono opacity-60">HTTP {quality.last_http_status}</span>}</span>})}</div><div className="ml-auto flex items-center gap-2">{problem&&<span className="hidden md:inline text-[10px] text-[#a0a4b5]">Une erreur marché ne signifie pas « aucun ordre ».</span>}<button type="button" onClick={onRefresh} disabled={isSyncing} className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-md border border-[#31333f] bg-[#0e1117] text-[10px] font-semibold text-[#cfd3dc] hover:text-white disabled:opacity-50"><RefreshCw className={'w-3 h-3 '+(isSyncing?'animate-spin':'')}/>{isSyncing?'Synchronisation…':'Actualiser'}</button></div></div></section>};
